using System;
namespace uber_uni.helpers.models
{
    // LanguageModel myDeserializedClass = JsonConvert.DeserializeObject<LanguageModel>(myJsonResponse); 
    public class LanguageModel
    {
        public string aa { get; set; }
        public string ab { get; set; }
        public string ace { get; set; }
        public string ach { get; set; }
        public string ada { get; set; }
        public string ady { get; set; }
        public string ae { get; set; }
        public string aeb { get; set; }
        public string af { get; set; }
        public string afh { get; set; }
        public string agq { get; set; }
        public string ain { get; set; }
        public string ak { get; set; }
        public string akk { get; set; }
        public string akz { get; set; }
        public string ale { get; set; }
        public string aln { get; set; }
        public string alt { get; set; }
        public string am { get; set; }
        public string an { get; set; }
        public string ang { get; set; }
        public string anp { get; set; }
        public string ar { get; set; }
        public string ar_001 { get; set; }
        public string arc { get; set; }
        public string arn { get; set; }
        public string aro { get; set; }
        public string arp { get; set; }
        public string arq { get; set; }
        public string ars { get; set; }
        public string arw { get; set; }
        public string ary { get; set; }
        public string arz { get; set; }
        public string @as { get; set; }
        public string asa { get; set; }
        public string ase { get; set; }
        public string ast { get; set; }
        public string av { get; set; }
        public string avk { get; set; }
        public string awa { get; set; }
        public string ay { get; set; }
        public string az { get; set; }
        public string ba { get; set; }
        public string bal { get; set; }
        public string ban { get; set; }
        public string bar { get; set; }
        public string bas { get; set; }
        public string bax { get; set; }
        public string bbc { get; set; }
        public string bbj { get; set; }
        public string be { get; set; }
        public string bej { get; set; }
        public string bem { get; set; }
        public string bew { get; set; }
        public string bez { get; set; }
        public string bfd { get; set; }
        public string bfq { get; set; }
        public string bg { get; set; }
        public string bgn { get; set; }
        public string bho { get; set; }
        public string bi { get; set; }
        public string bik { get; set; }
        public string bin { get; set; }
        public string bjn { get; set; }
        public string bkm { get; set; }
        public string bla { get; set; }
        public string bm { get; set; }
        public string bn { get; set; }
        public string bo { get; set; }
        public string bpy { get; set; }
        public string bqi { get; set; }
        public string br { get; set; }
        public string bra { get; set; }
        public string brh { get; set; }
        public string brx { get; set; }
        public string bs { get; set; }
        public string bss { get; set; }
        public string bua { get; set; }
        public string bug { get; set; }
        public string bum { get; set; }
        public string byn { get; set; }
        public string byv { get; set; }
        public string ca { get; set; }
        public string cad { get; set; }
        public string car { get; set; }
        public string cay { get; set; }
        public string cch { get; set; }
        public string ce { get; set; }
        public string ceb { get; set; }
        public string cgg { get; set; }
        public string ch { get; set; }
        public string chb { get; set; }
        public string chg { get; set; }
        public string chk { get; set; }
        public string chm { get; set; }
        public string chn { get; set; }
        public string cho { get; set; }
        public string chp { get; set; }
        public string chr { get; set; }
        public string chy { get; set; }
        public string ckb { get; set; }
        public string co { get; set; }
        public string cop { get; set; }
        public string cps { get; set; }
        public string cr { get; set; }
        public string crh { get; set; }
        public string crs { get; set; }
        public string cs { get; set; }
        public string csb { get; set; }
        public string cu { get; set; }
        public string cv { get; set; }
        public string cy { get; set; }
        public string da { get; set; }
        public string dak { get; set; }
        public string dar { get; set; }
        public string dav { get; set; }
        public string de { get; set; }
        public string de_AT { get; set; }
        public string de_CH { get; set; }
        public string del { get; set; }
        public string den { get; set; }
        public string dgr { get; set; }
        public string din { get; set; }
        public string dje { get; set; }
        public string doi { get; set; }
        public string dsb { get; set; }
        public string dtp { get; set; }
        public string dua { get; set; }
        public string dum { get; set; }
        public string dv { get; set; }
        public string dyo { get; set; }
        public string dyu { get; set; }
        public string dz { get; set; }
        public string dzg { get; set; }
        public string ebu { get; set; }
        public string ee { get; set; }
        public string efi { get; set; }
        public string egl { get; set; }
        public string egy { get; set; }
        public string eka { get; set; }
        public string el { get; set; }
        public string elx { get; set; }
        public string en { get; set; }
        public string en_AU { get; set; }
        public string en_CA { get; set; }
        public string en_GB { get; set; }
        public string en_US { get; set; }
        public string enm { get; set; }
        public string eo { get; set; }
        public string es { get; set; }
        public string es_419 { get; set; }
        public string es_ES { get; set; }
        public string es_MX { get; set; }
        public string esu { get; set; }
        public string et { get; set; }
        public string eu { get; set; }
        public string ewo { get; set; }
        public string ext { get; set; }
        public string fa { get; set; }
        public string fa_AF { get; set; }
        public string fan { get; set; }
        public string fat { get; set; }
        public string ff { get; set; }
        public string fi { get; set; }
        public string fil { get; set; }
        public string fit { get; set; }
        public string fj { get; set; }
        public string fo { get; set; }
        public string fon { get; set; }
        public string fr { get; set; }
        public string fr_CA { get; set; }
        public string fr_CH { get; set; }
        public string frc { get; set; }
        public string frm { get; set; }
        public string fro { get; set; }
        public string frp { get; set; }
        public string frr { get; set; }
        public string frs { get; set; }
        public string fur { get; set; }
        public string fy { get; set; }
        public string ga { get; set; }
        public string gaa { get; set; }
        public string gag { get; set; }
        public string gan { get; set; }
        public string gay { get; set; }
        public string gba { get; set; }
        public string gbz { get; set; }
        public string gd { get; set; }
        public string gez { get; set; }
        public string gil { get; set; }
        public string gl { get; set; }
        public string glk { get; set; }
        public string gmh { get; set; }
        public string gn { get; set; }
        public string goh { get; set; }
        public string gom { get; set; }
        public string gon { get; set; }
        public string gor { get; set; }
        public string got { get; set; }
        public string grb { get; set; }
        public string grc { get; set; }
        public string gsw { get; set; }
        public string gu { get; set; }
        public string guc { get; set; }
        public string gur { get; set; }
        public string guz { get; set; }
        public string gv { get; set; }
        public string gwi { get; set; }
        public string ha { get; set; }
        public string hai { get; set; }
        public string hak { get; set; }
        public string haw { get; set; }
        public string he { get; set; }
        public string hi { get; set; }
        public string hif { get; set; }
        public string hil { get; set; }
        public string hit { get; set; }
        public string hmn { get; set; }
        public string ho { get; set; }
        public string hr { get; set; }
        public string hsb { get; set; }
        public string hsn { get; set; }
        public string ht { get; set; }
        public string hu { get; set; }
        public string hup { get; set; }
        public string hy { get; set; }
        public string hz { get; set; }
        public string ia { get; set; }
        public string iba { get; set; }
        public string ibb { get; set; }
        public string id { get; set; }
        public string ie { get; set; }
        public string ig { get; set; }
        public string ii { get; set; }
        public string ik { get; set; }
        public string ilo { get; set; }
        public string inh { get; set; }
        public string io { get; set; }
        public string @is { get; set; }
        public string it { get; set; }
        public string iu { get; set; }
        public string izh { get; set; }
        public string ja { get; set; }
        public string jam { get; set; }
        public string jbo { get; set; }
        public string jgo { get; set; }
        public string jmc { get; set; }
        public string jpr { get; set; }
        public string jrb { get; set; }
        public string jut { get; set; }
        public string jv { get; set; }
        public string ka { get; set; }
        public string kaa { get; set; }
        public string kab { get; set; }
        public string kac { get; set; }
        public string kaj { get; set; }
        public string kam { get; set; }
        public string kaw { get; set; }
        public string kbd { get; set; }
        public string kbl { get; set; }
        public string kcg { get; set; }
        public string kde { get; set; }
        public string kea { get; set; }
        public string ken { get; set; }
        public string kfo { get; set; }
        public string kg { get; set; }
        public string kgp { get; set; }
        public string kha { get; set; }
        public string kho { get; set; }
        public string khq { get; set; }
        public string khw { get; set; }
        public string ki { get; set; }
        public string kiu { get; set; }
        public string kj { get; set; }
        public string kk { get; set; }
        public string kkj { get; set; }
        public string kl { get; set; }
        public string kln { get; set; }
        public string km { get; set; }
        public string kmb { get; set; }
        public string kn { get; set; }
        public string ko { get; set; }
        public string koi { get; set; }
        public string kok { get; set; }
        public string kos { get; set; }
        public string kpe { get; set; }
        public string kr { get; set; }
        public string krc { get; set; }
        public string kri { get; set; }
        public string krj { get; set; }
        public string krl { get; set; }
        public string kru { get; set; }
        public string ks { get; set; }
        public string ksb { get; set; }
        public string ksf { get; set; }
        public string ksh { get; set; }
        public string ku { get; set; }
        public string kum { get; set; }
        public string kut { get; set; }
        public string kv { get; set; }
        public string kw { get; set; }
        public string ky { get; set; }
        public string la { get; set; }
        public string lad { get; set; }
        public string lag { get; set; }
        public string lah { get; set; }
        public string lam { get; set; }
        public string lb { get; set; }
        public string lez { get; set; }
        public string lfn { get; set; }
        public string lg { get; set; }
        public string li { get; set; }
        public string lij { get; set; }
        public string liv { get; set; }
        public string lkt { get; set; }
        public string lmo { get; set; }
        public string ln { get; set; }
        public string lo { get; set; }
        public string lol { get; set; }
        public string loz { get; set; }
        public string lrc { get; set; }
        public string lt { get; set; }
        public string ltg { get; set; }
        public string lu { get; set; }
        public string lua { get; set; }
        public string lui { get; set; }
        public string lun { get; set; }
        public string luo { get; set; }
        public string lus { get; set; }
        public string luy { get; set; }
        public string lv { get; set; }
        public string lzh { get; set; }
        public string lzz { get; set; }
        public string mad { get; set; }
        public string maf { get; set; }
        public string mag { get; set; }
        public string mai { get; set; }
        public string mak { get; set; }
        public string man { get; set; }
        public string mas { get; set; }
        public string mde { get; set; }
        public string mdf { get; set; }
        public string mdr { get; set; }
        public string men { get; set; }
        public string mer { get; set; }
        public string mfe { get; set; }
        public string mg { get; set; }
        public string mga { get; set; }
        public string mgh { get; set; }
        public string mgo { get; set; }
        public string mh { get; set; }
        public string mi { get; set; }
        public string mic { get; set; }
        public string min { get; set; }
        public string mk { get; set; }
        public string ml { get; set; }
        public string mn { get; set; }
        public string mnc { get; set; }
        public string mni { get; set; }
        public string moh { get; set; }
        public string mos { get; set; }
        public string mr { get; set; }
        public string mrj { get; set; }
        public string ms { get; set; }
        public string mt { get; set; }
        public string mua { get; set; }
        public string mul { get; set; }
        public string mus { get; set; }
        public string mwl { get; set; }
        public string mwr { get; set; }
        public string mwv { get; set; }
        public string my { get; set; }
        public string mye { get; set; }
        public string myv { get; set; }
        public string mzn { get; set; }
        public string na { get; set; }
        public string nan { get; set; }
        public string nap { get; set; }
        public string naq { get; set; }
        public string nb { get; set; }
        public string nd { get; set; }
        public string nds { get; set; }
        public string nds_NL { get; set; }
        public string ne { get; set; }
        public string @new { get; set; }
        public string ng { get; set; }
        public string nia { get; set; }
        public string niu { get; set; }
        public string njo { get; set; }
        public string nl { get; set; }
        public string nl_BE { get; set; }
        public string nmg { get; set; }
        public string nn { get; set; }
        public string nnh { get; set; }
        public string no { get; set; }
        public string nog { get; set; }
        public string non { get; set; }
        public string nov { get; set; }
        public string nqo { get; set; }
        public string nr { get; set; }
        public string nso { get; set; }
        public string nus { get; set; }
        public string nv { get; set; }
        public string nwc { get; set; }
        public string ny { get; set; }
        public string nym { get; set; }
        public string nyn { get; set; }
        public string nyo { get; set; }
        public string nzi { get; set; }
        public string oc { get; set; }
        public string oj { get; set; }
        public string om { get; set; }
        public string or { get; set; }
        public string os { get; set; }
        public string osa { get; set; }
        public string ota { get; set; }
        public string pa { get; set; }
        public string pag { get; set; }
        public string pal { get; set; }
        public string pam { get; set; }
        public string pap { get; set; }
        public string pau { get; set; }
        public string pcd { get; set; }
        public string pcm { get; set; }
        public string pdc { get; set; }
        public string pdt { get; set; }
        public string peo { get; set; }
        public string pfl { get; set; }
        public string phn { get; set; }
        public string pi { get; set; }
        public string pl { get; set; }
        public string pms { get; set; }
        public string pnt { get; set; }
        public string pon { get; set; }
        public string prg { get; set; }
        public string pro { get; set; }
        public string ps { get; set; }
        public string pt { get; set; }
        public string pt_BR { get; set; }
        public string pt_PT { get; set; }
        public string qu { get; set; }
        public string quc { get; set; }
        public string qug { get; set; }
        public string raj { get; set; }
        public string rap { get; set; }
        public string rar { get; set; }
        public string rgn { get; set; }
        public string rif { get; set; }
        public string rm { get; set; }
        public string rn { get; set; }
        public string ro { get; set; }
        public string ro_MD { get; set; }
        public string rof { get; set; }
        public string rom { get; set; }
        public string root { get; set; }
        public string rtm { get; set; }
        public string ru { get; set; }
        public string rue { get; set; }
        public string rug { get; set; }
        public string rup { get; set; }
        public string rw { get; set; }
        public string rwk { get; set; }
        public string sa { get; set; }
        public string sad { get; set; }
        public string sah { get; set; }
        public string sam { get; set; }
        public string saq { get; set; }
        public string sas { get; set; }
        public string sat { get; set; }
        public string saz { get; set; }
        public string sba { get; set; }
        public string sbp { get; set; }
        public string sc { get; set; }
        public string scn { get; set; }
        public string sco { get; set; }
        public string sd { get; set; }
        public string sdc { get; set; }
        public string sdh { get; set; }
        public string se { get; set; }
        public string see { get; set; }
        public string seh { get; set; }
        public string sei { get; set; }
        public string sel { get; set; }
        public string ses { get; set; }
        public string sg { get; set; }
        public string sga { get; set; }
        public string sgs { get; set; }
        public string sh { get; set; }
        public string shi { get; set; }
        public string shn { get; set; }
        public string shu { get; set; }
        public string si { get; set; }
        public string sid { get; set; }
        public string sk { get; set; }
        public string sl { get; set; }
        public string sli { get; set; }
        public string sly { get; set; }
        public string sm { get; set; }
        public string sma { get; set; }
        public string smj { get; set; }
        public string smn { get; set; }
        public string sms { get; set; }
        public string sn { get; set; }
        public string snk { get; set; }
        public string so { get; set; }
        public string sog { get; set; }
        public string sq { get; set; }
        public string sr { get; set; }
        public string srn { get; set; }
        public string srr { get; set; }
        public string ss { get; set; }
        public string ssy { get; set; }
        public string st { get; set; }
        public string stq { get; set; }
        public string su { get; set; }
        public string suk { get; set; }
        public string sus { get; set; }
        public string sux { get; set; }
        public string sv { get; set; }
        public string sw { get; set; }
        public string sw_CD { get; set; }
        public string swb { get; set; }
        public string syc { get; set; }
        public string syr { get; set; }
        public string szl { get; set; }
        public string ta { get; set; }
        public string tcy { get; set; }
        public string te { get; set; }
        public string tem { get; set; }
        public string teo { get; set; }
        public string ter { get; set; }
        public string tet { get; set; }
        public string tg { get; set; }
        public string th { get; set; }
        public string ti { get; set; }
        public string tig { get; set; }
        public string tiv { get; set; }
        public string tk { get; set; }
        public string tkl { get; set; }
        public string tkr { get; set; }
        public string tl { get; set; }
        public string tlh { get; set; }
        public string tli { get; set; }
        public string tly { get; set; }
        public string tmh { get; set; }
        public string tn { get; set; }
        public string to { get; set; }
        public string tog { get; set; }
        public string tpi { get; set; }
        public string tr { get; set; }
        public string tru { get; set; }
        public string trv { get; set; }
        public string ts { get; set; }
        public string tsd { get; set; }
        public string tsi { get; set; }
        public string tt { get; set; }
        public string ttt { get; set; }
        public string tum { get; set; }
        public string tvl { get; set; }
        public string tw { get; set; }
        public string twq { get; set; }
        public string ty { get; set; }
        public string tyv { get; set; }
        public string tzm { get; set; }
        public string udm { get; set; }
        public string ug { get; set; }
        public string uga { get; set; }
        public string uk { get; set; }
        public string umb { get; set; }
        public string und { get; set; }
        public string ur { get; set; }
        public string uz { get; set; }
        public string vai { get; set; }
        public string ve { get; set; }
        public string vec { get; set; }
        public string vep { get; set; }
        public string vi { get; set; }
        public string vls { get; set; }
        public string vmf { get; set; }
        public string vo { get; set; }
        public string vot { get; set; }
        public string vro { get; set; }
        public string vun { get; set; }
        public string wa { get; set; }
        public string wae { get; set; }
        public string wal { get; set; }
        public string war { get; set; }
        public string was { get; set; }
        public string wbp { get; set; }
        public string wo { get; set; }
        public string wuu { get; set; }
        public string xal { get; set; }
        public string xh { get; set; }
        public string xmf { get; set; }
        public string xog { get; set; }
        public string yao { get; set; }
        public string yap { get; set; }
        public string yav { get; set; }
        public string ybb { get; set; }
        public string yi { get; set; }
        public string yo { get; set; }
        public string yrl { get; set; }
        public string yue { get; set; }
        public string za { get; set; }
        public string zap { get; set; }
        public string zbl { get; set; }
        public string zea { get; set; }
        public string zen { get; set; }
        public string zgh { get; set; }
        public string zh { get; set; }
        public string zh_Hans { get; set; }
        public string zh_Hant { get; set; }
        public string zu { get; set; }
        public string zun { get; set; }
        public string zxx { get; set; }
        public string zza { get; set; }
    }


}
